# Dependabot Configuration
# https://docs.github.com/code-security/supply-chain-security/configuration-options-for-dependency-updates
#

version: 2

updates:
- package-ecosystem: "npm"
  # Files stored in repository docs
  directory: "/"
  schedule:
    interval: "daily"
#   ignore:
#   - dependency-name: "packagesToIgnore"
